### ISSUE TITLE
src and tgt in data preparation?

### ISSUE THREAD

**Issue by kkenealy** [rpryzant/delete_retrieve_generate#13]
Hi,

Could you clarify what are the intended uses of the source and target files in the data preparation section in the README? I'm a bit confused, because it seems like in the reference paper, there is no target sentence for each source sentence, but rather just sentences and labels. If so, what should be the source and target here? Thank you!

**Comment by rpryzant** [comment]
Thanks for asking! src and tgt are the names for sentences of each label type. For example positive reviews could be label A and negative could be label B. Then you put all the A's and B's together to keep organized during training.
