### ISSUE TITLE
editdistance package is not installed with requirements.txt

### ISSUE THREAD

**Issue by alper111** [rpryzant/delete_retrieve_generate#15]
I have installed the required packages in a new virtual environment created with anaconda. `editdistance` package is not installed.

**Comment by rpryzant** [comment]
Hmm can you explain your setup in a little more detail?
that package is in the requirements file (https://github.com/rpryzant/delete_retrieve_generate/blob/b9163512af92bc99dfd0c81c1a2affd9d580b1ae/requirements.txt) 
and I just checked that it installed correctly on my machine.

**Comment by alper111** [comment]
With my pip, it couldn't find torch 1.1.0 then I manually installed 1.4.0. I thought pip has already installed other packages in requirements (since torch comes after editdistance)  but I guess it didn't. I tried it again and now it worked. It cannot find torch 1.1.0 though, I changed it to 1.4.0. Thank you for your quick response.

pip version=20.0.2
python version=3.8
