### ISSUE TITLE
Inference Mode

### ISSUE THREAD

**Issue by abhinavkashyap** [rpryzant/delete_retrieve_generate#17]
Hi, 

Thank you for this implementation. Is there any script that can load lines from a text file and perform inference on the trained model ?

The `evaluate.inference_metrics` is useful only when there is a reference test dataset. If we do not have one, is there a way to use the model for inference on sentences ?

**Comment by rpryzant** [comment]
So what you can do is point `src_test` and `tgt_test` at the same file in your config:
https://github.com/rpryzant/delete_retrieve_generate/blob/master/yelp_config.json#L14

and then the metrics will be screwed up but the system should properly perform inference on the source senences:
https://github.com/rpryzant/delete_retrieve_generate/blob/master/train.py#L75

**Comment by abhinavkashyap** [comment]
Thanks for that :) Yes. I did that...but the best model is saved according to the BLEU score. That needs a change when there is no reference dataset. Also, It becomes difficult to test on different sentences once the model is trained. We will have to train the model every time we want to test on a new dataset. :) It would be good if there is a way for just loading the model and taking the sentences. If I can help in any way to achieve this, that would be good :)

**Comment by rpryzant** [comment]
I see, I added an inference file, hopefully that should satisfy your request! 

https://github.com/rpryzant/delete_retrieve_generate/blob/master/inference.py

**Comment by abhinavkashyap** [comment]
Thank you for the quick responses. I really appreciate it. I will give it a try and update this thread. Thank you
