### ISSUE TITLE
delete_retrieve taking long time + the BLEU scores different from the paper

### ISSUE THREAD

**Issue by anthammas** [rpryzant/delete_retrieve_generate#26]
Hello. I am trying to run the 'delete_retrieve' model for the yelp dataset with the same config given in the code. I just set the 
`"model_type": "delete_retrieve"`

However, I see that the model is taking infinite time for just the first iteration

```
2021-05-04 22:12:07,463 - INFO - MODEL HAS 10364933 params
2021-05-04 22:12:13,904 - INFO - EPOCH: 0 ITER: 0.0/692.2578125 EPS: 8830.61 LOSS: 9.1699 METRIC: 0.0000
```
and it's freezing there. Is there any other parameter in the config or any other file that I need to tweak to run the 'delete_retrieve' efficiently. Also, do we need 70 epochs here or can be lesser?

**Comment by rpryzant** [comment]
Thanks for reaching out. Hmm...are you running  this on a GPU? The `delete_retrieve` model is indeed slow, but it shouldn't hang forever. Each epoch  should take a few hours on a gpu.

**Comment by anthammas** [comment]
Well thank you @rpryzant. As you mentioned, the delete_retrieve mode is just slow but is working fine.
May I know the BLEU score you obtained for YELP dataset using DeleteOnly and DeleteAndRetrieve?

For the DeleteOnly model, I have obtained a BLEU score of 16.46 using the test data of YELP (reference.test.0 in your code) when comparing against the human annotation YELP data (reference.test.1). However, I see in the paper the score for DeleteOnly is 7.5. 

And also, is there any classifier in the code to measure the style transfer strength ?

**Comment by rpryzant** [comment]
Hello, I've added a [FAQ section to the README](https://github.com/rpryzant/delete_retrieve_generate#why-cant-i-get-the-same-bleu-score-as-the-original-paper) which addresses this. Let me know if you have any other questions!

**Comment by anthammas** [comment]
Thank you @rpryzant :)

**Comment by anthammas** [comment]
Will close this issue
