### ISSUE TITLE
yelp_config.json should contain "data" as key by default instead of "paper_data"

### ISSUE THREAD

**Issue by c0dzilla** [rpryzant/delete_retrieve_generate#3]
Not sure if this has been done on purpose. Nevertheless, since `data` is the actual name of the directory, it makes more sense to use it instead of `paper_data` as the default directory name everywhere inside `config_yelp.json`? Avoids an unnecessary tweaking for people using this directly.

**Comment by rpryzant** [comment]
Ah thanks for the catch! Fixed: https://github.com/rpryzant/delete_retrieve_generate/commit/a77fbd8ab1f61e36220f2c476d459c4c97249d5c
