### ISSUE TITLE
How to show the example outputs?

### ISSUE THREAD

**Issue by wasedaward** [rpryzant/delete_retrieve_generate#34]
Hi, 
Thank you for this implementation. 
After I trained models. I want to input a negative source sentence to see the effect of the output positive sentence. Is there any script that can achieve that? 
like this:
![drg](https://user-images.githubusercontent.com/84557605/137167562-2cc794c2-bfc3-40c5-abd0-69191cdfae5d.png)
Thank you very much!

**Comment by rpryzant** [comment]
Yes! see the inference instructions here: https://github.com/rpryzant/delete_retrieve_generate#inference
