### ISSUE TITLE
Can I run Retrieve-Only and Template-Based mode with your code?

### ISSUE THREAD

**Issue by Karlguo** [rpryzant/delete_retrieve_generate#7]
Hi, There are 4 modes in the original paper: Delete-Only, Delete-and-Retrieve, Retrieve-Only and Template-Based, but I only find Delete-Only, Delete-and-Retrieve in your code. Can I find other 2 modes, too?

**Comment by rpryzant** [comment]
Nope! Not implemented yet. Feel free to submit it as a pull request :)
