### ISSUE TITLE
How to select sentences from candidates?

### ISSUE THREAD

**Issue by wusj18** [rpryzant/delete_retrieve_generate#8]
In the paper, author said he used a separate trained classifier to choose the final sentence from all the candidates that model produced. How did you deal with this part? Thank you very much!

**Comment by rpryzant** [comment]
Can you point me to where that classifier is discussed in the paper?

If you're talking about the classifier in section 4.7 there may be a misunderstanding because that classifier is used for evaluation, not re-ranking candidates.

**Comment by wusj18** [comment]
At the end of Section 4.4, author said "For DELETEANDRETRIEVE, similar to Guu et al. (2018), we retrieve the top-10 sentences and generate results using markers from each sentence. We then select the output with the lowest perplexity given by a separately-trained neural language model on the target-domain training data."
I think this may improve the performance. Thanks for your reply

**Comment by rpryzant** [comment]
Ah I see thanks for pointing that out!

That feature is not implemented. So in effect we are greedily selecting and using markers from the top result for DeleteAndRetrieve.  

I agree that it may improve performance. Feel free to submit it as a pull request :)

**Comment by wusj18** [comment]
I will have a try, thanks again! :-)
